app/blog/models.py
from email.policy import default
from app.extensions.database import db, CRUDMixin
from datetime import datetime


class Blog(db.Model, CRUDMixin):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    content = db.Column(db.String(800))
    picture_url = db.Column(db.String(200))
    date = db.Column(db.Date, nullable=False,
                     default=datetime.date(datetime.utcnow()))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

app/projects/models.py
from app.extensions.database import db, CRUDMixin


class Project(db.Model, CRUDMixin):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    description = db.Column(db.String(300))
    gh_link = db.Column(db.String(200))
    image_link = db.Column(db.String(200))

app/users/models.py
from app.extensions.database import db, CRUDMixin
from flask_login import UserMixin


class User(db.Model, CRUDMixin, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    name = db.Column(db.String(100))
    passwd = db.Column(db.String(300))
    blogs = db.relationship("Blog", backref="user", lazy=True)

app/app.py
import os
from flask import Flask, render_template
from app.extensions.database import db, migrate
from app.extensions.authentication import login_manager

from . import simple_pages
from . import projects
from . import blog
from . import users


def create_app():
    app = Flask(__name__)
    app.config.from_object('app.config')

    register_extensions(app)
    register_blueprints(app)

    return app


def register_blueprints(app: Flask):
    app.register_blueprint(projects.routes.blueprint)
    app.register_blueprint(blog.routes.blueprint)
    app.register_blueprint(simple_pages.routes.blueprint)
    app.register_blueprint(users.routes.blueprint)


def register_extensions(app: Flask):
    db.init_app(app)
    migrate.init_app(app, db, render_as_batch=True)
    login_manager.init_app(app)

app/blog/routes.py
import imp
from flask import Blueprint, redirect, render_template, request, url_for, current_app
from .models import Blog
from .services import *
from app.users.models import User
from flask_login import login_required, current_user

blueprint = Blueprint('blogs', __name__)

# Routes


@blueprint.route('/blogs')
def blogs():
    page_number = request.args.get('page', 1, type=int)
    blogs_pagination = Blog.query.paginate(
        page_number, current_app.config['POSTS_PER_PAGE'])
    return render_template('blog/blogs.html', blogs_pagination=blogs_pagination, page_number=page_number)


@blueprint.get('/blogs/<int:id>')
def get_blog(id):
    blog = Blog.query.get(id)
    user = User.query.get(blog.user_id)

    return render_template(
        'blog/blog.html',
        blog=blog,
        user=user
    )


@blueprint.post('/blogs/<int:id>')
@login_required
def delete_blog(id):
    blog = Blog.query.get(id)
    blog.delete()
    return redirect(url_for('blogs.blogs'))

# Edit current blog post


@blueprint.get('/blogs/<int:id>/edit')
@login_required
def get_edit_blog(id):
    blog = Blog.query.get(id)
    return render_template('blog/edit_blog.html', blog=blog)


@blueprint.post('/blogs/<int:id>/edit')
@login_required
def edit_blog(id):
    blog = Blog.query.get(id)
    update_post(request.form, blog)
    return redirect(url_for('blogs.get_blog', id=blog.id))


@blueprint.get('/blogs/new')
@login_required
def get_blogs():
    return render_template(
        'blog/new_blog.html',
    )


@blueprint.post('/blogs/new')
@login_required
def new_blog():
    try:
        blog_id = save_post(request.form, current_user)
        blog_id
        return redirect(url_for('blogs.get_blog', id=blog_id))

    except Exception as error_message:
        error = error_message or 'An error occurred while creating a post. Please make sure to enter valid data.'
        return render_template(
            'blog/new_blog.html',
            error=error
        )

app/projects/__init__.py
from . import routes, models

app/projects/routes.py
from flask import Blueprint, redirect, render_template, request, url_for
from .models import Project
from .services import *
from flask_login import login_required

blueprint = Blueprint('projects', __name__)

# Routes


@blueprint.route('/projects')
def projects():
    all_projects = Project.query.all()
    return render_template('projects/projects.html', projects=all_projects)


@blueprint.get('/projects/<id>/edit')
@login_required
def get_project(id):
    project = Project.query.get(id)
    return render_template(
        'projects/project.html',
        project=project
    )


@blueprint.post('/projects/<int:id>/edit')
@login_required
def update_project(id):
    project = Project.query.get(id)
    update(request.form, project)
    return redirect(url_for('projects.projects'))


@blueprint.post('/projects/<int:id>')
@login_required
def delete_project(id):
    project = Project.query.get(id)
    project.delete()
    return redirect(url_for('projects.projects'))


@blueprint.get('/projects/new')
@login_required
def new_project():
    return render_template(
        'projects/new_project.html'
    )


@blueprint.post('/projects/new')
@login_required
def post_project():
    create_project(request.form)
    return redirect(url_for('projects.projects'))

app/simple_pages/__init__.py
from . import routes

app/simple_pages/routes.py
from flask import Blueprint, render_template

blueprint = Blueprint('/', __name__)


@blueprint.route('/')
@blueprint.route('/home')
def home():
    return render_template('home.html')


@blueprint.route('/contact')
def contact():
    return render_template('contact.html')

app/users/__init__.py
from . import models, routes

app/users/routes.py
from .models import User
from flask import Blueprint, redirect, render_template, request, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required
from .services import *

blueprint = Blueprint('users', __name__)


@blueprint.get('/register')
@login_required
def get_register():
    return render_template('users/register.html')


@blueprint.post('/register')
@login_required
def post_register():
    try:
        register(request.form)
        return redirect(url_for('users.get_login'))

    except Exception as error_message:
        error = error_message or 'An error occurred while creating a user. Please make sure to enter valid data.'
        return render_template('users/register.html', error=error)


@blueprint.get('/login')
def get_login():
    return render_template('users/login.html')


@blueprint.post('/login')
def post_login():
    try:
        login(request.form)
        return redirect(url_for('blog.blogs'))

    except Exception as error_message:
        error = error_message or 'An error occurred while logging in. Please verify your email and password.'
        return render_template('users/login.html', error=error)


@blueprint.get('/logout')
def logout():
    logout_user()

    return redirect(url_for('users.get_login'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>:~$ {% block title %}{% endblock %}</title>

    <!-- Javascript files -->
    <script src="{{ url_for('static',filename='js/darkMode.js') }}" defer></script>
    <script src="{{ url_for('static',filename='js/menu.js') }}" defer></script>
    <script src="https://kit.fontawesome.com/f6088cc271.js" crossorigin="anonymous"></script>
    <!-- <script defer src="{{ url_for('static',filename='js/scripts.js') }}" crossorigin="anonymous"></script> -->

    <!-- CSS files -->
    <!-- <link defer rel="stylesheet" href="{{ url_for('static',filename='css/styles.css') }}"> -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/buttons.css') }}">

    {% endblock %}
</head>

<body>
    <!-- Navigation menu -->
    {% block nav %}
    <nav>
        <div class="logo-container">
            <a href="/" id="logo" class="">
                :<span id="tilde">~</span>$ Camila Martinez<span id="cursor">_</span>
            </a>
        </div>
        <button id="hamburger-button">
            <span class="sr-only">Menu</span>
            <i class="fa-solid fa-bars"></i>
        </button>
        <div class="primary-menu">
            <ul class="navigation">
                <li>
                    <button type="button" id="theme-switcher">
                        <i class="fa-solid fa-circle" id="switch"></i>
                        <i class="fa-solid fa-sun" id="sun-icon"></i>
                        <i class="fa-solid fa-moon" id="moon-icon"></i>
                    </button>
                </li>
                <li>
                    <a href="/projects" id="menu-item">Projects</a>
                </li>
                <li>
                    <a href="/blogs" id="menu-item">Blog</a>
                </li>
                <li>
                    <a href="/contact" id="menu-item">Contact</a>
                </li>
                {% if current_user.is_anonymous %}
                <li>
                    <a href="/login">
                        <button id="login-btn">
                            Login
                        </button>
                    </a>
                </li>
                {% endif %}
                {% if current_user.is_authenticated %}
                <li>
                    <small id="login-status">
                        <a href="{{ url_for('users.logout') }}">
                            <button class="logout-btn">
                                Logout
                            </button>
                        </a>
                        {{ current_user.name }}
                    </small>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="mobile-menu">
            <!-- This is where navigation will go depending on screen size -->
        </div>
    </nav>
    {% endblock %}

    <!-- Content -->
    <div class="container">
        {% block header %}
        {% endblock %}


        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

app/templates/blog/blog.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='css/blog.css') }}">
{% endblock %}

{% block nav %}
{{ super() }}
{% endblock %}

{% block header %}
<div class="header">
    <h1>
        {% block title %} {{ blog.title }} {% endblock %}
    </h1>
    <div>
        <h5>{{user.name}}</h5>
        <h6>{{blog.date}}</h6>
    </div>
</div>
{% if current_user.is_authenticated %}
<div class="edit-btn-container">
    <a href="/blogs/{{blog.id}}/edit">
        <button>Edit</button>
    </a>
</div>
{%endif%}
{% endblock %}

{% block content %}
<div class="blog-post">
    <div class="single-blog-info">
        <div class="post-img-container">
            <img src="{{blog.picture_url}}" alt="header img" id="post-header-img">
        </div>
        <p id="single-blog-description">
            {{ blog.content }}
        </p>
    </div>
</div>
{% endblock %}

app/templates/blog/blogs.html
{% extends "base.html" %}
{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='css/blog.css') }}">
{% endblock %}

{% block nav %}
{{ super() }}
{% endblock %}


{% block header %}
<div class="header">
    <h1>
        {% block title %}
        Blog 📝
        {% endblock %}
    </h1>
    {% if current_user.is_authenticated %}
    <a href="blogs/new" id="page-link">
        <button>Create a post</button>
    </a>
    {% endif %}
</div>
{% endblock %}

{% block content %}
{% if not blogs_pagination.items %}
<h4 id="no-posts">No posts yet</h4>
{% else %}
{% for blog in blogs_pagination.items %}
<div class="blog">
    <div class="blog-body">
        <h2 id="blog-title">
            {{ blog.title }}
        </h2>
        <p id="blog-description">
            {{ blog.content[0:100] }} ...
        </p>
        <a href="blogs/{{blog.id}}" id="blog-link">
            <button type="button">Read more</button>
        </a>
    </div>
    <div class="blog-img-container">
        <img id="blog-img" src="{{blog.picture_url}}">
    </div>
</div>
{% endfor %}
{% endif %}

{% if blogs_pagination.items %}
<div id="pagination">
    {% if blogs_pagination.prev_num %}
    <a href="/blogs?page={{ blogs_pagination.prev_num }}">
        <i class="fa-solid fa-arrow-left-long"></i>
        Previous
    </a>
    {%endif%}
    <span> - {{page_number}} - </span>
    {% if blogs_pagination.next_num %}
    <a href="/blogs?page={{ blogs_pagination.next_num }}">
        Next
        <i class="fa-solid fa-arrow-right-long"></i>
    </a>
    {%endif%}
</div>
{% endif %}
{% endblock %}

app/templates/blog/edit_blog.html
{% extends "base.html" %}
{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='css/blog.css') }}">

{% endblock %}

{% block nav %}
{{ super() }}
{% endblock %}

{% block header %}
<div class="header">
  <h2>
    {% block title %}
    Edit Post
    {% endblock %}
  </h2>
  <div>
    <form method="post" id="delete-form" action="{{ url_for('blogs.delete_blog', id=blog.id) }}">
      <button type="submit" id="delete-btn">Delete</button>
    </form>
  </div>
</div>
{% endblock %}

{% block content %}
{% if error %}
<div class="error">
  <p style="color: tomato; text-align: center;">{{ error }}</p>
</div>
{% endif %}
<div class="blog-form-container">
  <form method="post">
    <div class="input-container">
      <label for="title">Title:</label>
      <br>
      <input type="text" name="title" id="title" value="{{ request.form['title'] or blog.title }}">
    </div>
    <div class="input-container">
      <label for="content">Content:</label>
      <br>
      <textarea name="content" id="content">{{ request.form['content'] or blog.content }}</textarea>
    </div>
    <div class="input-container">
      <label for="picture_url">Header image URL:</label>
      <br>
      <input type="text" name="picture_url" id="picture_url"
        value="{{ request.form['picture_url'] or blog.picture_url }}">
    </div>
    <div class="btn-container">
      <button type="submit" class="input-btn">Save</button>
    </div>
  </form>
</div>

{% endblock %}

app/templates/blog/new_blog.html
{% extends "base.html" %}
{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='css/blog.css') }}">

{% endblock %}

{% block nav %}
{{ super() }}
{% endblock %}

{% block header %}
<div class="header">
  <h2>
    {% block title %}
    New Blog Post
    {% endblock %}
  </h2>
</div>
{% endblock %}

{% block content %}
{% if error %}
<div class="error">
  <p style="color: tomato; text-align: center;">{{ error }}</p>
</div>
{% endif %}
<div class="blog-form-container">
  <form method="post">
    <div class="input-container">
      <label for="title">Title:</label>
      <br>
      <input type="text" name="title" id="title" placeholder="Learning Flask">
    </div>
    <div class="input-container">
      <label for="content">Content:</label>
      <br>
      <textarea name="content" id="content" placeholder="Insert text here...">{{ request.form['content'] }}</textarea>
    </div>
    <div class="input-container">
      <label for="picture_url">Header image URL:</label>
      <br>
      <input type="text" name="picture_url" id="picture_url" placeholder="https://www.image.com/image.jpg"
        value="{{ request.form['picture_url'] }}">
    </div>
    <div class="btn-container">
      <button type="submit" class="input-btn">Add</button>
    </div>
  </form>
</div>

{% endblock %}

app/templates/contact.html
{% extends "base.html" %}
{% block title %}Contact 💻{% endblock %}
{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='css/contact.css') }}">
{% endblock %}

{% block nav %}
{{ super() }}
{% endblock %}

{% block content %}
<div class="contact-container">
    <h1>💻 Get in touch</h1>
    <ul id="links-list">
        <li><a href="mailto:camilamarb98@gmail.com">
                <i class="fa-solid fa-envelope"></i>
                <p>
                    Email
                </p>
            </a></li>
        <li><a href="https://github.com/cammarb">
                <i class="fa-brands fa-github"></i>
                <p>

                    Github
                </p>
            </a> </li>
        <li><a href="https://www.linkedin.com/in/camila-mart%C3%ADnez-bedoya-5b43011a2/">
                <i class="fa-brands fa-linkedin"></i>
                <p>
                    LinkedIn
                </p>
            </a> </li>
    </ul>
    <div class="btn-container">
        <a href="https://drive.google.com/file/d/1g3VvV9IFTMimCN0cXFjga67IaK3a0bcX/view?usp=sharing" id="resume-btn">
            <button>
                My resume
            </button>
        </a>
    </div>
</div>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}
{% block title %}Home 🏠{% endblock %}
{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='css/home.css') }}">
{% endblock %}

{% block nav %}
{{ super() }}
{% endblock %}

{% block content %}
<div class="home-header">
	<div class="column" id="left-col">
		<h1>
			Hi👋
			<br>
			I'm Camila
		</h1>
		<br>
		<h3>Software Engineering student</h3>
		<h4>Lima, PE -> 📍 Berlin, DE</h4>
		<div id="languages-container">
			<h5 class="programming-language" id="py">
				<i class="fa-brands fa-python"></i>
				Python
			</h5>
			<h5 class="programming-language" id="js">
				<i class="fa-brands fa-js"></i>
				Javascript
			</h5>
			<h5 class="programming-language" id="java">
				<i class="fa-brands fa-java"></i>
				Java
			</h5>
			<h5 class="programming-language" id="cs">
				C# CSharp
			</h5>
		</div>
		<div class="btn-projects-container">
			<a href="projects">
				<button>
					Projects
				</button>
			</a>
		</div>
	</div>
	<div class="column" id="right-col">
		<img src="../static/img/laptop.png" alt="laptop" title="laptop icon" id="laptop-img">
	</div>
</div>
<div class="github-link">
	<a href="https://github.com/cammarb" id="github-anchor">
		Check out my
		<span id="github" style="background: none;">
			<i class="fa-brands fa-github"></i>
			GitHub
		</span>
		page!
	</a>
</div>
{% endblock %}

app/templates/projects/new_project.html
{% extends "base.html" %}
{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='css/projects.css') }}">
{% endblock %}

{% block nav %}
{{ super() }}
{% endblock %}

{% block header %}
<div class="header">
  <h2>
    {% block title %}
    Add Project
    {% endblock %}
  </h2>
</div>
{% endblock %}


{% block content %}
<div class="project">

  <form method="post">
    <div class="input-container">
      <label for="title">Title:</label>
      <br>

      <input type="text" name="title" id="title" placeholder="My awesome app" value="{{ request.form['title'] }}">
    </div>
    <div class="input-container">
      <label for="description">Description:</label>
      <br>

      <textarea name="description" id="description"
        placeholder="Insert description here...">{{ request.form['description'] }}</textarea>
    </div>
    <div class="input-container">
      <label for="image_link">Image URL:</label>
      <br>

      <input type="text" name="image_link" id="image_link" placeholder="https://www.image.com/image.jpg"
        value="{{ request.form['image_link'] }}">
    </div>
    <div class="input-container">
      <label for="gh_link">Github URL:</label>
      <br>

      <input type="text" name="gh_link" id="gh_link" placeholder="https://www.github.com/awesome.git"
        value="{{ request.form['gh_link'] }}">
    </div>
    <div class="btn-container">
      <button type="submit" class="input-btn">Add </button>
    </div>
  </form>
</div>

{% endblock %}

app/templates/projects/project.html
{% extends "base.html" %}
{% block title %} {{ project.title }} {% endblock %}
{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='css/projects.css') }}">
{% endblock %}

{% block nav %}
{{ super() }}
{% endblock %}

{% block header %}
<div class="header">
    <h1>
        Project #{{project.id}}
    </h1>
    <div>
        <form method="post" id="delete-form" action="{{ url_for('projects.delete_project', id=project.id) }}">
            <button type="submit" id="delete-btn">Delete</button>
        </form>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="project">
    <form method="post">
        <div class="input-container">
            <label for="title">Title:</label>
            <br>

            <input type="text" name="title" id="title" placeholder="My awesome app"
                value="{{ request.form['title'] or project.title }}">
        </div>
        <div class="input-container">
            <label for="description">Description:</label>
            <br>

            <textarea name="description" id="description"
                placeholder="Insert description here...">{{ request.form['description'] or project.description }}</textarea>
        </div>
        <div class="input-container">
            <label for="image_link">Image URL:</label>
            <br>

            <input type="text" name="image_link" id="image_link" placeholder="https://www.image.com/image.jpg"
                value="{{ request.form['image_link'] or project.image_link }}">
        </div>
        <div class="input-container">
            <label for="gh_link">Github URL:</label>
            <br>

            <input type="text" name="gh_link" id="gh_link" placeholder="https://www.github.com/awesome.git"
                value="{{ request.form['gh_link'] or project.gh_link }}">
        </div>
        <div class="btn-container">
            <button type="submit" class="input-btn">Save</button>
        </div>
    </form>
</div>
{% endblock %}

app/templates/projects/projects.html
{% extends "base.html" %}
{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='css/projects.css') }}">
{% endblock %}

{% block nav %}
{{ super() }}
{% endblock %}

{% block header %}
<div class="header">
    <h1>
        {% block title %}
        Projects 📁
        {% endblock %}
    </h1>
    {% if current_user.is_authenticated %}
    <a href="projects/new">
        <button>Add a project</button>
    </a>
    {% endif %}
</div>
{% endblock %}


{% block content %}
{% for project in projects %}
<div class="project-container">
    <div class="project-info">
        <h2 id="project-title">{{ project.title }}</h2>
        <p id="project-description">
            {{ project.description }}
        </p>
        <div class="links-row">
            <div class="project-links">
                <a href="{{project.gh_link}}" class="repo-link">
                    <i class="fa-brands fa-github" id="github-icon"></i>
                    Repository
                </a>
            </div>
            {% if current_user.is_authenticated %}
            <a href="/projects/{{project.id}}/edit">
                <button>Manage</button>
            </a>
            {% endif %}
        </div>
    </div>
    <div class="project-img-container">
        <img src="{{project.image_link}}" alt="project screenshot" title="project screenshot" id="project-img">
    </div>
</div>
{% endfor %}
{% endblock %}

app/templates/users/login.html
{% extends 'base.html' %}
{% block head %}
{{super()}}
<link rel="stylesheet" href="{{ url_for('static', filename='css/login-forms.css') }}">
{% endblock %}

{% block header %}
<div class="header">
    <h2>
        {% block title %}Login{% endblock %}
    </h2>
</div>
{% endblock %}

{% block content %}
<div class="login-register">
    <form method="post">
        <div class="input-container">
            <label for="email">Email:</label>
            <br>
            <input type="email" name="email">
        </div>
        <div class="input-container">
            <label for="password">Password:</label>
            <br>
            <input type="password" name="password">
        </div>

        <div class="btn-container">
            <button type="submit" class="input-btn">Login</button>
        </div>

    </form>
</div>
{% endblock %}

app/templates/users/register.html
{% extends 'base.html' %}
{% block head %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/login-forms.css')}}">
{% endblock %}

{% block header %}
<div class="header">
    <h2>
        {% block title %}Register{% endblock %}
    </h2>
    <div>
        {% if error %}
        <p style="color: tomato;">{{ error }}</p>
        {% endif %}
    </div>
</div>
{% endblock %}
{% block content %}
<div class="login-register">
    <form method="post">
        <div class="input-container">
            <label for="name">Full name:</label>
            <br>
            <input type="text" name="name" id="name" required>
        </div>
        <div class="input-container">
            <label for="email">Email:</label>
            <br>
            <input type="email" name="email" id="email" required>
        </div>

        <div class="input-container">
            <label for="password">Password:</label>
            <br>
            <input type="password" name="password" id="password" required>
        </div>

        <div class="input-container">
            <label for="password_confirmation">Password Confirmation:</label>
            <br>
            <input type="password" name="password_confirmation" id="password_confirmation" required>
        </div>
        <div class="btn-container">
            <button type="submit" class="input-btn">Register</button>
        </div>
    </form>
</div>
{% endblock %}